spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieclub
    username: root
    password: admin
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/, file:C:\Users\robin\uploads
#                   's'                      nie ma roznicy  '/'  '\'
app:
  storage:
    location: C:/Users/robin/uploads/
